name: sengor-karic-local

services:
  api:
    build:
      dockerfile: ./apps/api/Dockerfile
      target: local
    env_file: ./apps/api/.env.local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:5050"
    develop:
      watch:
        - action: sync+restart
          path: ./apps/api
          target: /app/apps/api
          ignore:
            - ./apps/api/node_modules/
            - ./apps/api/build/
        - action: rebuild
          path: ./apps/api/package.json
          target: /app/apps/api

  web:
    build:
      dockerfile: ./apps/web/Dockerfile
      target: local
    env_file: ./apps/web/.env.local
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /app/apps/web
          ignore:
            - ./apps/web/node_modules/
            - ./apps/web/build/
            - ./apps/web/.react-router/

  db:
    image: postgres:17.2
    restart: always
    env_file: ./apps/api/.env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  db_data: